# 自动生成的 mpn 目录的源文件列表
# 生成时间: 2026-01-06 15:13:42
# 目录: mpn
# 说明: 此文件由脚本自动生成，包含所有子目录中的.c文件（保留路径）

MPN_SRCS := $(addprefix mpn/, \
	add.c \
	add_1.c \
	add_err1_n.c \
	add_err2_n.c \
	add_err3_n.c \
	add_n.c \
	add_n_sub_n.c \
	addmul_1.c \
	and_n.c \
	andn_n.c \
	bdiv_dbm1c.c \
	bdiv_q.c \
	bdiv_q_1.c \
	bdiv_qr.c \
	binvert.c \
	broot.c \
	brootinv.c \
	bsqrt.c \
	bsqrtinv.c \
	cmp.c \
	cnd_add_n.c \
	cnd_sub_n.c \
	cnd_swap.c \
	com.c \
	comb_tables.c \
	compute_powtab.c \
	copyd.c \
	copyi.c \
	dcpi1_bdiv_q.c \
	dcpi1_bdiv_qr.c \
	dcpi1_div_q.c \
	dcpi1_div_qr.c \
	dcpi1_divappr_q.c \
	div_q.c \
	div_qr_1.c \
	div_qr_1n_pi1.c \
	div_qr_2.c \
	div_qr_2n_pi1.c \
	div_qr_2u_pi1.c \
	dive_1.c \
	diveby3.c \
	divexact.c \
	divis.c \
	divrem.c \
	divrem_1.c \
	divrem_2.c \
	dump.c \
	fib2_ui.c \
	fib2m.c \
	fib_table.c \
	gcd.c \
	gcd_1.c \
	gcd_11.c \
	gcd_22.c \
	gcd_subdiv_step.c \
	gcdext.c \
	gcdext_1.c \
	gcdext_lehmer.c \
	get_d.c \
	get_str.c \
	hamdist.c \
	hgcd.c \
	hgcd2.c \
	hgcd2_jacobi.c \
	hgcd_appr.c \
	hgcd_jacobi.c \
	hgcd_matrix.c \
	hgcd_reduce.c \
	hgcd_step.c \
	invert.c \
	invertappr.c \
	ior_n.c \
	iorn_n.c \
	jacbase.c \
	jacobi.c \
	jacobi_2.c \
	lshift.c \
	lshiftc.c \
	matrix22_mul.c \
	matrix22_mul1_inverse_vector.c \
	mod_1.c \
	mod_1_1.c \
	mod_1_2.c \
	mod_1_3.c \
	mod_1_4.c \
	mod_34lsub1.c \
	mode1o.c \
	mp_bases.c \
	mu_bdiv_q.c \
	mu_bdiv_qr.c \
	mu_div_q.c \
	mu_div_qr.c \
	mu_divappr_q.c \
	mul.c \
	mul_1.c \
	mul_basecase.c \
	mul_fft.c \
	mul_n.c \
	mullo_basecase.c \
	mullo_n.c \
	mulmid.c \
	mulmid_basecase.c \
	mulmid_n.c \
	mulmod_bnm1.c \
	nand_n.c \
	neg.c \
	nior_n.c \
	nussbaumer_mul.c \
	perfpow.c \
	perfsqr.c \
	popcount.c \
	pow_1.c \
	powlo.c \
	powm.c \
	pre_divrem_1.c \
	pre_mod_1.c \
	random.c \
	random2.c \
	redc_1.c \
	redc_2.c \
	redc_n.c \
	remove.c \
	rootrem.c \
	rshift.c \
	sbpi1_bdiv_q.c \
	sbpi1_bdiv_qr.c \
	sbpi1_bdiv_r.c \
	sbpi1_div_q.c \
	sbpi1_div_qr.c \
	sbpi1_divappr_q.c \
	scan0.c \
	scan1.c \
	sec_add_1.c \
	sec_div_qr.c \
	sec_div_r.c \
	sec_invert.c \
	sec_mul.c \
	sec_pi1_div_qr.c \
	sec_pi1_div_r.c \
	sec_powm.c \
	sec_sqr.c \
	sec_sub_1.c \
	sec_tabselect.c \
	set_str.c \
	sizeinbase.c \
	sqr.c \
	sqr_basecase.c \
	sqrlo.c \
	sqrlo_basecase.c \
	sqrmod_bnm1.c \
	sqrtrem.c \
	strongfibo.c \
	sub.c \
	sub_1.c \
	sub_err1_n.c \
	sub_err2_n.c \
	sub_err3_n.c \
	sub_n.c \
	submul_1.c \
	tdiv_qr.c \
	toom22_mul.c \
	toom2_sqr.c \
	toom32_mul.c \
	toom33_mul.c \
	toom3_sqr.c \
	toom42_mul.c \
	toom42_mulmid.c \
	toom43_mul.c \
	toom44_mul.c \
	toom4_sqr.c \
	toom52_mul.c \
	toom53_mul.c \
	toom54_mul.c \
	toom62_mul.c \
	toom63_mul.c \
	toom6_sqr.c \
	toom6h_mul.c \
	toom8_sqr.c \
	toom8h_mul.c \
	toom_couple_handling.c \
	toom_eval_dgr3_pm1.c \
	toom_eval_dgr3_pm2.c \
	toom_eval_pm1.c \
	toom_eval_pm2.c \
	toom_eval_pm2exp.c \
	toom_eval_pm2rexp.c \
	toom_interpolate_12pts.c \
	toom_interpolate_16pts.c \
	toom_interpolate_5pts.c \
	toom_interpolate_6pts.c \
	toom_interpolate_7pts.c \
	toom_interpolate_8pts.c \
	trialdiv.c \
	xnor_n.c \
	xor_n.c \
	zero.c \
	zero_p.c \
)
