// This file is auto-generated by Inliner. Do not edit manually.
#ifndef IMAGE_STORE_PRESS_TO_TEST_SUCCESS_H
#define IMAGE_STORE_PRESS_TO_TEST_SUCCESS_H

#include <escher/image.h>

namespace ImageStore {

extern const Escher::Image * const PressToTestSuccess;

};

#endif
