// This file is auto-generated by Inliner. Do not edit manually.
#ifndef IMAGE_STORE_CARTESIAN_GRID_ICON_H
#define IMAGE_STORE_CARTESIAN_GRID_ICON_H

#include <escher/image.h>

namespace ImageStore {

extern const Escher::Image * const CartesianGridIcon;

};

#endif
