set(COMPONENT_NAME ion)

# 源文件列表（支持通配符或明确列表）
set(MODULE_SOURCES
        #src/device/shared/boot/rt0.cpp
        src/device/shared/drivers/assert.cpp
        src/device/shared/drivers/board_unprivileged.cpp
        src/device/shared/drivers/console_display.cpp
        src/device/shared/drivers/dfu_interfaces.cpp
        src/device/shared/drivers/flash_information.cpp
        src/device/shared/drivers/read_only_memory.cpp
        src/device/shared/drivers/trampoline.cpp
        src/device/shared/drivers/usb_unprivileged.cpp
        #src/device/shared/flash/board.cpp
        src/device/shared/post_and_hardware_tests.cpp
        src/device/shared/usb/calculator.cpp
        src/device/shared/usb/calculator_userland_leave_reset.cpp
        src/device/shared/usb/dfu_interface.cpp
        src/device/shared/usb/dfu_xip.cpp
        src/device/shared/usb/stack/descriptor/bos_descriptor.cpp
        src/device/shared/usb/stack/descriptor/configuration_descriptor.cpp
        src/device/shared/usb/stack/descriptor/descriptor.cpp
        src/device/shared/usb/stack/descriptor/device_capability_descriptor.cpp
        src/device/shared/usb/stack/descriptor/device_descriptor.cpp
        src/device/shared/usb/stack/descriptor/dfu_functional_descriptor.cpp
        src/device/shared/usb/stack/descriptor/extended_compat_id_descriptor.cpp
        src/device/shared/usb/stack/descriptor/interface_descriptor.cpp
        src/device/shared/usb/stack/descriptor/language_id_string_descriptor.cpp
        src/device/shared/usb/stack/descriptor/microsoft_os_string_descriptor.cpp
        src/device/shared/usb/stack/descriptor/platform_device_capability_descriptor.cpp
        src/device/shared/usb/stack/descriptor/string_descriptor.cpp
        src/device/shared/usb/stack/descriptor/url_descriptor.cpp
        src/device/shared/usb/stack/descriptor/webusb_platform_descriptor.cpp
        src/device/shared/usb/stack/device.cpp
        src/device/shared/usb/stack/device_otg.cpp
        src/device/shared/usb/stack/endpoint0_otg.cpp
        src/device/shared/usb/stack/interface.cpp
        src/device/shared/usb/stack/request_recipient.cpp
        src/device/shared/usb/stack/setup_packet.cpp
        src/device/shared/usb/stack/streamable.cpp
        src/device/userland/boot/isr.cpp
        src/device/userland/boot/rt0.cpp
        src/device/userland/drivers/authentication.cpp
        src/device/userland/drivers/backlight.cpp
        src/device/userland/drivers/battery.cpp
        src/device/userland/drivers/board.cpp
        src/device/userland/drivers/board_dual_slots.cpp
        src/device/userland/drivers/board_ram_dfu_xip.cpp
        src/device/userland/drivers/circuit_breaker.cpp
        src/device/userland/drivers/clipboard.cpp
        src/device/userland/drivers/compilation_flags.cpp
        src/device/userland/drivers/crc32.cpp
        src/device/userland/drivers/device_name.cpp
        src/device/userland/drivers/display.cpp
        src/device/userland/drivers/events.cpp
        src/device/userland/drivers/exam_bytes.cpp
        src/device/userland/drivers/fcc_id.cpp
        src/device/userland/drivers/flash_write_with_interruptions.cpp
        src/device/userland/drivers/init.cpp
        src/device/userland/drivers/keyboard.cpp
        src/device/userland/drivers/led.cpp
        src/device/userland/drivers/pcb_version.cpp
        src/device/userland/drivers/persisting_bytes.cpp
        src/device/userland/drivers/power.cpp
        src/device/userland/drivers/random.cpp
        src/device/userland/drivers/reset.cpp
        src/device/userland/drivers/reset_svcall.cpp
        src/device/userland/drivers/serial_number.cpp
        src/device/userland/drivers/serial_number_svcall.cpp
        src/device/userland/drivers/stack.cpp
        src/device/userland/drivers/timing.cpp
        src/device/userland/drivers/usb.cpp
        src/device/userland/drivers/usb_svcall.cpp
        src/device/userland/drivers/userland_header.cpp
        src/shared/collect_registers.cpp
        src/shared/console_line.cpp
        src/shared/display_context.cpp
        src/shared/dummy/external_apps.cpp
        src/shared/exam_mode.cpp
        src/shared/stack_position.cpp
        src/shared/storage/file_system.cpp
        src/shared/storage/record.cpp
        src/shared/storage/record_name_verifier.cpp
        )

# 注册为IDF组件
idf_component_register(
        SRCS ${MODULE_SOURCES}
        INCLUDE_DIRS "include"
            ${CMAKE_CURRENT_LIST_DIR}/include  # 绝对路径
            ${CMAKE_CURRENT_LIST_DIR}/..
            ${CMAKE_CURRENT_SOURCE_DIR}/../ion/include/ion/keyboard/epsilon
            ${CMAKE_CURRENT_LIST_DIR}/src/device
            ${CMAKE_CURRENT_LIST_DIR}/src/device/include/n0120
            ${CMAKE_CURRENT_SOURCE_DIR}/../omg/include
            ${CMAKE_CURRENT_SOURCE_DIR}/../kandinsky/include
       REQUIRES
            omg
            kandinsky
)
