// This file is auto-generated by Inliner. Do not edit manually.
#ifndef IMAGE_STORE_SIGNIFICANCE_TEST_H
#define IMAGE_STORE_SIGNIFICANCE_TEST_H

#include <escher/image.h>

namespace ImageStore {

extern const Escher::Image * const SignificanceTest;

};

#endif
