set(COMPONENT_NAME mpfi)

# 源文件列表（支持通配符或明确列表）
set(MODULE_SOURCES
        src/abs.c
        src/acos.c
        src/acosh.c
        src/add.c
        src/add_d.c
        src/add_fr.c
        src/add_q.c
        src/add_si.c
        src/add_ui.c
        src/add_z.c
        src/alea.c
        src/asin.c
        src/asinh.c
        src/atan.c
        src/atan2.c
        src/atanh.c
        src/bisect.c
        src/blow.c
        src/cbrt.c
        src/clear.c
        src/clears.c
        src/cmp.c
        src/cmp_sym_pi.c
        src/constants.c
        src/cos.c
        src/cosh.c
        src/cot.c
        src/coth.c
        src/csc.c
        src/csch.c
        src/d_div.c
        src/d_sub.c
        src/diam.c
        src/div.c
        src/div_2exp.c
        src/div_2si.c
        src/div_2ui.c
        src/div_d.c
        src/div_ext.c
        src/div_fr.c
        src/div_q.c
        src/div_si.c
        src/div_ui.c
        src/div_z.c
        src/erandom.c
        src/error.c
        src/exp.c
        src/exp10.c
        src/exp10m1.c
        src/exp2.c
        src/exp2m1.c
        src/expm1.c
        src/fr_div.c
        src/fr_sub.c
        src/get_d.c
        src/get_endpoints.c
        src/get_fr.c
        src/get_prec.c
        src/get_version.c
        src/has_zero.c
        src/hypot.c
        src/increase.c
        src/init.c
        src/init2.c
        src/inits.c
        src/inits2.c
        src/inp_str.c
        src/intersect.c
        src/interv_d.c
        src/interv_fr.c
        src/interv_q.c
        src/interv_si.c
        src/interv_ui.c
        src/interv_z.c
        src/inv.c
        src/is_empty.c
        src/is_inside.c
        src/log.c
        src/log10.c
        src/log10p1.c
        src/log1p.c
        src/log2.c
        src/log2p1.c
        src/mag.c
        src/mid.c
        src/mig.c
        src/mul.c
        src/mul_2exp.c
        src/mul_2si.c
        src/mul_2ui.c
        src/mul_d.c
        src/mul_fr.c
        src/mul_q.c
        src/mul_si.c
        src/mul_ui.c
        src/mul_z.c
        src/neg.c
        src/nrandom.c
        src/out_str.c
        src/predicates.c
        src/print_binary.c
        src/put.c
        src/put_d.c
        src/put_fr.c
        src/put_q.c
        src/put_si.c
        src/put_ui.c
        src/put_z.c
        src/q_div.c
        src/q_sub.c
        src/quadrant.c
        src/rec_sqrt.c
        src/revert_if_needed.c
        src/round_prec.c
        src/sec.c
        src/sech.c
        src/set.c
        src/set_d.c
        src/set_flt.c
        src/set_fr.c
        src/set_ld.c
        src/set_prec.c
        src/set_q.c
        src/set_si.c
        src/set_str.c
        src/set_ui.c
        src/set_z.c
        src/si_div.c
        src/si_sub.c
        src/sign.c
        src/sin.c
        src/sinh.c
        src/sqr.c
        src/sqrt.c
        src/sub.c
        src/sub_d.c
        src/sub_fr.c
        src/sub_q.c
        src/sub_si.c
        src/sub_ui.c
        src/sub_z.c
        src/swap.c
        src/tan.c
        src/tanh.c
        src/ui_div.c
        src/ui_sub.c
        src/union.c
        src/urandom.c
        src/z_div.c
        src/z_sub.c
        )

# 注册为IDF组件
idf_component_register(
        SRCS ${MODULE_SOURCES}
        INCLUDE_DIRS
            ${CMAKE_CURRENT_LIST_DIR}/include
            ${CMAKE_CURRENT_LIST_DIR}
            # ${CMAKE_CURRENT_LIST_DIR}/src
            ${CMAKE_CURRENT_LIST_DIR}/../gmp/include
            ${CMAKE_CURRENT_LIST_DIR}/../mpfr/include
        REQUIRES mpfr           # 依赖的组件gmp
)
target_compile_options(${COMPONENT_LIB} PRIVATE
        -Os
        --specs=nosys.specs
        "-Wno-error=unused-value" "-Wno-error=char-subscripts" "-Wno-error=array-parameter=")
