# 自动生成的 apps 目录的源文件列表
# 生成时间: 2025-12-26 15:32:43
# 目录: apps
# 说明: 此文件由脚本自动生成，包含所有子目录中的.c文件（保留路径）

APPS_SRCS := $(addprefix apps/, \
	apps_container.c \
	apps_container_helper.c \
	apps_container_launch_default.c \
	apps_container_prompt_none.c \
	apps_container_storage.c \
	apps_window.c \
	backlight_dimming_timer.c \
	battery_timer.c \
	battery_view.c \
	calculation/additional_results/additional_results_controller.c \
	calculation/additional_results/additional_results_type.c \
	calculation/additional_results/chained_expressions_list_controller.c \
	calculation/additional_results/complex_graph_cell.c \
	calculation/additional_results/complex_list_controller.c \
	calculation/additional_results/complex_model.c \
	calculation/additional_results/expressions_list_controller.c \
	calculation/additional_results/function_graph_cell.c \
	calculation/additional_results/function_list_controller.c \
	calculation/additional_results/function_model.c \
	calculation/additional_results/illustrated_expressions_list_controller.c \
	calculation/additional_results/illustration_cell.c \
	calculation/additional_results/integer_list_controller.c \
	calculation/additional_results/layout_with_equal_sign_view.c \
	calculation/additional_results/matrix_list_controller.c \
	calculation/additional_results/rational_list_controller.c \
	calculation/additional_results/scientific_notation_list_controller.c \
	calculation/additional_results/scrollable_three_layouts_view.c \
	calculation/additional_results/trigonometry_graph_cell.c \
	calculation/additional_results/trigonometry_list_controller.c \
	calculation/additional_results/trigonometry_model.c \
	calculation/additional_results/unit_comparison_helper.c \
	calculation/additional_results/unit_list_controller.c \
	calculation/additional_results/vector_graph_cell.c \
	calculation/additional_results/vector_helper.c \
	calculation/additional_results/vector_list_controller.c \
	calculation/additional_results/vector_model.c \
	calculation/app.c \
	calculation/calculation.c \
	calculation/calculation_icon.c \
	calculation/calculation_selectable_list_view.c \
	calculation/calculation_store.c \
	calculation/edit_expression_controller.c \
	calculation/history_controller.c \
	calculation/history_view_cell.c \
	calculation/layout_field.c \
	code/app.c \
	code/clipboard.c \
	code/code_icon.c \
	code/console_controller.c \
	code/console_edit_cell.c \
	code/console_line_cell.c \
	code/console_store.c \
	code/editor_controller.c \
	code/editor_view.c \
	code/helpers.c \
	code/menu_controller.c \
	code/python_text_area.c \
	code/python_toolbox_controller.c \
	code/python_variable_box_controller.c \
	code/sandbox_controller.c \
	code/script.c \
	code/script_name_cell.c \
	code/script_parameter_controller.c \
	code/script_store.c \
	code/script_template.c \
	code/subtitle_cell.c \
	distributions/app.c \
	distributions/controllers/calculation_cell.c \
	distributions/controllers/calculation_controller.c \
	distributions/controllers/calculation_popup_data_source.c \
	distributions/controllers/distribution_controller.c \
	distributions/controllers/distribution_curve_view.c \
	distributions/controllers/parameters_controller.c \
	distributions/distributions_icon.c \
	distributions/images/binomial_icon.c \
	distributions/images/calculation1_icon.c \
	distributions/images/calculation2_icon.c \
	distributions/images/calculation3_icon.c \
	distributions/images/calculation4_icon.c \
	distributions/images/chi_squared_icon.c \
	distributions/images/exponential_icon.c \
	distributions/images/fisher_icon.c \
	distributions/images/geometric_icon.c \
	distributions/images/hypergeometric_icon.c \
	distributions/images/normal_icon.c \
	distributions/images/poisson_icon.c \
	distributions/images/student_icon.c \
	distributions/images/uniform_icon.c \
	distributions/models/calculation/calculation.c \
	distributions/models/calculation/discrete_calculation.c \
	distributions/models/calculation/finite_integral_calculation.c \
	distributions/models/calculation/left_integral_calculation.c \
	distributions/models/calculation/right_integral_calculation.c \
	distributions/models/distribution/binomial_distribution.c \
	distributions/models/distribution/chi_squared_distribution.c \
	distributions/models/distribution/distribution.c \
	distributions/models/distribution/exponential_distribution.c \
	distributions/models/distribution/fisher_distribution.c \
	distributions/models/distribution/hypergeometric_distribution.c \
	distributions/models/distribution/normal_distribution.c \
	distributions/models/distribution/poisson_distribution.c \
	distributions/models/distribution/student_distribution.c \
	distributions/models/distribution/uniform_distribution.c \
	elements/app.c \
	elements/banner_view.c \
	elements/data_field.c \
	elements/details_list_controller.c \
	elements/display_type_controller.c \
	elements/elements_data_base.c \
	elements/elements_icon.c \
	elements/elements_view.c \
	elements/elements_view_data_source.c \
	elements/main_controller.c \
	elements/single_element_view.c \
	elements/suggestion_text_field.c \
	elements/table_layout.c \
	empty_battery_window.c \
	exam_icon.c \
	exam_pop_up_controller.c \
	finance/app.c \
	finance/data.c \
	finance/finance_icon.c \
	finance/interest_menu_controller.c \
	finance/menu_controller.c \
	finance/parameters_controller.c \
	finance/result_controller.c \
	global_preferences.c \
	graph/app.c \
	graph/graph/area_between_curves_graph_controller.c \
	graph/graph/area_between_curves_parameter_controller.c \
	graph/graph/banner_view.c \
	graph/graph/calculation_graph_controller.c \
	graph/graph/calculation_parameter_controller.c \
	graph/graph/curve_parameter_controller.c \
	graph/graph/extremum_graph_controller.c \
	graph/graph/graph_controller.c \
	graph/graph/graph_controller_helper.c \
	graph/graph/graph_view.c \
	graph/graph/integral_graph_controller.c \
	graph/graph/interest_view.c \
	graph/graph/intersection_graph_controller.c \
	graph/graph/points_of_interest_cache.c \
	graph/graph/preimage_graph_controller.c \
	graph/graph/preimage_parameter_controller.c \
	graph/graph/root_graph_controller.c \
	graph/graph/tangent_graph_controller.c \
	graph/graph_icon.c \
	graph/list/editable_function_cell.c \
	graph/list/function_cell.c \
	graph/list/function_models_parameter_controller.c \
	graph/list/list_controller.c \
	graph/shared/derivative_column_parameter_controller.c \
	graph/shared/derivatives_parameter_controller.c \
	graph/shared/details_parameter_controller.c \
	graph/shared/domain_parameter_controller.c \
	graph/shared/function_parameter_controller.c \
	graph/values/interval_parameter_selector_controller.c \
	graph/values/values_controller.c \
	hardware_test/app.c \
	hardware_test/arrow_view.c \
	hardware_test/battery_test_controller.c \
	hardware_test/code_128b_view.c \
	hardware_test/colors_lcd_test_controller.c \
	hardware_test/dead_pixels_test_controller.c \
	hardware_test/keyboard_model.c \
	hardware_test/keyboard_test_controller.c \
	hardware_test/keyboard_view.c \
	hardware_test/lcd_data_test_controller.c \
	hardware_test/lcd_timing_test_controller.c \
	hardware_test/led_test_controller.c \
	hardware_test/serial_number_controller.c \
	hardware_test/vblank_test_controller.c \
	home/app.c \
	home/app_cell.c \
	home/apps_layout.c \
	home/controller.c \
	i18n.c \
	inference/app.c \
	inference/controllers/categorical_cell.c \
	inference/controllers/categorical_controller.c \
	inference/controllers/categorical_table_cell.c \
	inference/controllers/chi_square/categorical_type_controller.c \
	inference/controllers/chi_square/homogeneity_data_source.c \
	inference/controllers/chi_square/input_goodness_controller.c \
	inference/controllers/chi_square/input_goodness_table_cell.c \
	inference/controllers/chi_square/input_homogeneity_controller.c \
	inference/controllers/chi_square/input_homogeneity_table_cell.c \
	inference/controllers/chi_square/results_goodness_controller.c \
	inference/controllers/chi_square/results_goodness_table_cell.c \
	inference/controllers/chi_square/results_homogeneity_controller.c \
	inference/controllers/chi_square/results_homogeneity_table_cell.c \
	inference/controllers/comparison_operator_popup_data_source.c \
	inference/controllers/confidence_interval/interval_conclusion_view.c \
	inference/controllers/confidence_interval/interval_curve_view.c \
	inference/controllers/confidence_interval/interval_graph_controller.c \
	inference/controllers/confidence_interval/interval_graph_view.c \
	inference/controllers/dataset_controller.c \
	inference/controllers/dynamic_cells_data_source.c \
	inference/controllers/input_controller.c \
	inference/controllers/results_controller.c \
	inference/controllers/significance_test/hypothesis_controller.c \
	inference/controllers/significance_test/legend_view.c \
	inference/controllers/significance_test/test_curve_view.c \
	inference/controllers/significance_test/test_graph_controller.c \
	inference/controllers/significance_test/test_graph_view.c \
	inference/controllers/significance_test/zoom_hint_view.c \
	inference/controllers/store/input_store_controller.c \
	inference/controllers/store/store_table_cell.c \
	inference/controllers/test_controller.c \
	inference/controllers/type_controller.c \
	inference/images/confidence_interval.c \
	inference/images/significance_test.c \
	inference/inference_icon.c \
	inference/models/chi2_test.c \
	inference/models/confidence_interval.c \
	inference/models/goodness_test.c \
	inference/models/homogeneity_test.c \
	inference/models/inference_model.c \
	inference/models/input_table.c \
	inference/models/input_table_from_store.c \
	inference/models/one_mean_statistic.c \
	inference/models/significance_test.c \
	inference/models/slope_t_statistic.c \
	inference/models/two_means_statistic.c \
	init.c \
	lock_view.c \
	main.c \
	on_boarding/app.c \
	on_boarding/localization_controller.c \
	on_boarding/startup_prompt_controller.c \
	regression/app.c \
	regression/data/store_controller.c \
	regression/data/store_parameter_controller.c \
	regression/graph/banner_view.c \
	regression/graph/go_to_parameter_controller.c \
	regression/graph/graph_controller.c \
	regression/graph/graph_options_controller.c \
	regression/graph/graph_view.c \
	regression/graph/regression_controller.c \
	regression/graph/residual_plot_controller.c \
	regression/graph/residual_plot_curve_view.c \
	regression/graph/residual_plot_range.c \
	regression/model.c \
	regression/regression_icon.c \
	regression/stats/calculation_controller.c \
	regression/stats/column_title_cell.c \
	regression/stats/even_odd_double_buffer_text_cell.c \
	regression/store.c \
	sequence/app.c \
	sequence/graph/cobweb_controller.c \
	sequence/graph/cobweb_graph_view.c \
	sequence/graph/curve_parameter_controller.c \
	sequence/graph/curve_view_range.c \
	sequence/graph/go_to_parameter_controller.c \
	sequence/graph/graph_controller.c \
	sequence/graph/graph_view.c \
	sequence/graph/term_sum_controller.c \
	sequence/list/editable_sequence_cell.c \
	sequence/list/list_controller.c \
	sequence/list/list_parameter_controller.c \
	sequence/list/sequence_cell.c \
	sequence/list/sequence_toolbox_data_source.c \
	sequence/list/type_parameter_controller.c \
	sequence/sequence_icon.c \
	sequence/values/interval_parameter_controller.c \
	sequence/values/sequence_column_parameter_controller.c \
	sequence/values/sum_column_parameter_controller.c \
	sequence/values/values_controller.c \
	settings/app.c \
	settings/main_controller.c \
	settings/main_controller_prompt_none.c \
	settings/settings_icon.c \
	settings/sub_menu/about_controller.c \
	settings/sub_menu/display_mode_controller.c \
	settings/sub_menu/exam_mode_controller.c \
	settings/sub_menu/generic_sub_controller.c \
	settings/sub_menu/localization_controller.c \
	settings/sub_menu/preferences_controller.c \
	settings/sub_menu/press_to_test_controller.c \
	settings/sub_menu/press_to_test_success.c \
	settings/sub_menu/screen_timeout_controller.c \
	settings/sub_menu/selectable_view_with_messages.c \
	settings/sub_menu/test_mode_controller.c \
	shared/app_with_store_menu.c \
	shared/banner_view.c \
	shared/buffer_function_title_cell.c \
	shared/color_cell.c \
	shared/color_names.c \
	shared/color_parameter_controller.c \
	shared/column_helper.c \
	shared/column_parameter_controller.c \
	shared/continuous_function.c \
	shared/continuous_function_cache.c \
	shared/continuous_function_properties.c \
	shared/continuous_function_store.c \
	shared/curve_selection_controller.c \
	shared/curve_view_cursor.c \
	shared/curve_view_range.c \
	shared/dots.c \
	shared/double_pair_store.c \
	shared/double_pair_table_controller.c \
	shared/editable_cell_table_view_controller.c \
	shared/explicit_float_parameter_controller.c \
	shared/expression_function_title_cell.c \
	shared/expression_model.c \
	shared/expression_model_handle.c \
	shared/expression_model_list_controller.c \
	shared/expression_model_store.c \
	shared/expression_parameter_controller.c \
	shared/float_parameter_controller.c \
	shared/formula_template_menu_controller.c \
	shared/function.c \
	shared/function_app.c \
	shared/function_banner_delegate.c \
	shared/function_go_to_parameter_controller.c \
	shared/function_graph_controller.c \
	shared/function_graph_view.c \
	shared/function_list_controller.c \
	shared/function_name_helper.c \
	shared/function_title_cell.c \
	shared/function_zoom_and_pan_curve_view_controller.c \
	shared/global_context.c \
	shared/go_to_parameter_controller.c \
	shared/grid_type_controller.c \
	shared/images/cartesian_grid_icon.c \
	shared/images/polar_grid_icon.c \
	shared/interactive_curve_view_controller.c \
	shared/interactive_curve_view_range.c \
	shared/interactive_curve_view_range_delegate.c \
	shared/interval.c \
	shared/interval_parameter_controller.c \
	shared/linear_regression_store.c \
	shared/list_parameter_controller.c \
	shared/localization_controller.c \
	shared/math_field_delegate.c \
	shared/math_toolbox_content.c \
	shared/math_toolbox_controller.c \
	shared/math_variable_box_controller.c \
	shared/memoized_cursor_view.c \
	shared/memoized_curve_view_range.c \
	shared/menu_controller.c \
	shared/ok_view.c \
	shared/packed_range_1D.c \
	shared/parameter_text_field_delegate.c \
	shared/parameters_with_validation_controller.c \
	shared/plot_view.c \
	shared/plot_view_axes.c \
	shared/plot_view_banners.c \
	shared/plot_view_cursors.c \
	shared/plot_view_plots.c \
	shared/prompt_controller.c \
	shared/range_parameter_controller.c \
	shared/round_cursor_view.c \
	shared/sequence.c \
	shared/sequence_cache.c \
	shared/sequence_context.c \
	shared/sequence_store.c \
	shared/shared_app.c \
	shared/simple_interactive_curve_view_controller.c \
	shared/single_interactive_curve_view_range_controller.c \
	shared/single_range_controller.c \
	shared/statistical_distribution.c \
	shared/statistics_store.c \
	shared/store_app.c \
	shared/store_controller.c \
	shared/store_menu_controller.c \
	shared/store_parameter_controller.c \
	shared/sum_graph_controller.c \
	shared/tab_table_controller.c \
	shared/toolbox_helpers.c \
	shared/values_controller.c \
	shared/values_parameter_controller.c \
	shared/vertical_cursor_view.c \
	shared/zoom_and_pan_curve_view_controller.c \
	shared/zoom_curve_view_controller.c \
	shift_alpha_lock_view.c \
	solver/app.c \
	solver/equation.c \
	solver/equation_list_view.c \
	solver/equation_models_parameter_controller.c \
	solver/equation_store.c \
	solver/interval_controller.c \
	solver/list_controller.c \
	solver/solutions_controller.c \
	solver/solver_icon.c \
	solver/system_of_equations.c \
	statistics/app.c \
	statistics/box_icon.c \
	statistics/cumulative_icon.c \
	statistics/data/store_controller.c \
	statistics/data/store_parameter_controller.c \
	statistics/graph/box_banner_view.c \
	statistics/graph/box_controller.c \
	statistics/graph/box_parameter_controller.c \
	statistics/graph/box_range.c \
	statistics/graph/box_view.c \
	statistics/graph/chevrons.c \
	statistics/graph/data_view.c \
	statistics/graph/data_view_controller.c \
	statistics/graph/frequency_controller.c \
	statistics/graph/graph_type_controller.c \
	statistics/graph/graph_view_model.c \
	statistics/graph/histogram_banner_view.c \
	statistics/graph/histogram_cell.c \
	statistics/graph/histogram_list_controller.c \
	statistics/graph/histogram_main_controller.c \
	statistics/graph/histogram_main_view.c \
	statistics/graph/histogram_parameter_controller.c \
	statistics/graph/histogram_range.c \
	statistics/graph/histogram_view.c \
	statistics/graph/multiple_boxes_view.c \
	statistics/graph/multiple_data_view.c \
	statistics/graph/normal_probability_controller.c \
	statistics/graph/plot_banner_view.c \
	statistics/graph/plot_controller.c \
	statistics/graph/plot_curve_view.c \
	statistics/graph/plot_range.c \
	statistics/graph/plot_view.c \
	statistics/histogram_icon.c \
	statistics/stat_icon.c \
	statistics/statistics_normal_icon.c \
	statistics/stats/calculation_controller.c \
	statistics/stats/calculation_selectable_table_view.c \
	statistics/store.c \
	suspend_timer.c \
	title_bar_view.c \
	usb/app.c \
	usb/usb_connected_controller.c \
)
