# 自动生成的 escher 目录的源文件列表
# 生成时间: 2025-12-26 15:32:43
# 目录: escher
# 说明: 此文件由脚本自动生成，包含所有子目录中的.c文件（保留路径）

ESCHER_SRCS := $(addprefix escher/, \
	image/caret.c \
	src/abstract_text_field.c \
	src/alternate_empty_nested_menu_controller.c \
	src/alternate_empty_view_controller.c \
	src/alternate_view_controller.c \
	src/app.c \
	src/bank_view_controller.c \
	src/blink_timer.c \
	src/bordered.c \
	src/bordering_view.c \
	src/buffer_text_view.c \
	src/button_cell.c \
	src/button_row_controller.c \
	src/button_state.c \
	src/chained_text_field_delegate.c \
	src/chevron_view.c \
	src/clipboard.c \
	src/container.c \
	src/dropdown_view.c \
	src/editable_expression_cell.c \
	src/editable_expression_model_cell.c \
	src/editable_field.c \
	src/editable_text_cell.c \
	src/ellipsis_view.c \
	src/even_odd_buffer_text_cell.c \
	src/even_odd_cell.c \
	src/even_odd_cell_with_ellipsis.c \
	src/even_odd_editable_text_cell.c \
	src/even_odd_expression_cell.c \
	src/even_odd_message_text_cell.c \
	src/explicit_list_view_data_source.c \
	src/expression_input_bar.c \
	src/gauge_view.c \
	src/glyphs_view.c \
	src/heavy_table_size_manager.c \
	src/highlight_cell.c \
	src/highlight_image_cell.c \
	src/horizontal_or_vertical_layout.c \
	src/image_view.c \
	src/init.c \
	src/input_view_controller.c \
	src/invocation.c \
	src/key_view.c \
	src/layout_field.c \
	src/layout_view.c \
	src/list_view_data_source.c \
	src/list_with_top_and_bottom_controller.c \
	src/menu_cell.c \
	src/menu_cell_with_editable_text.c \
	src/message_text_view.c \
	src/message_view.c \
	src/modal_view_controller.c \
	src/modal_view_empty_controller.c \
	src/nested_menu_controller.c \
	src/palette.c \
	src/pointer_text_view.c \
	src/pop_up_controller.c \
	src/preface_data_source.c \
	src/prefaced_table_view.c \
	src/prefaced_twice_table_view.c \
	src/responder.c \
	src/run_loop.c \
	src/scroll_view.c \
	src/scroll_view_data_source.c \
	src/scroll_view_indicator.c \
	src/scrollable_layout_view.c \
	src/scrollable_multiple_layouts_view.c \
	src/scrollable_two_layouts_cell.c \
	src/scrollable_view.c \
	src/selectable_list_view.c \
	src/selectable_list_view_controller.c \
	src/selectable_list_view_delegate.c \
	src/selectable_table_view.c \
	src/selectable_table_view_delegate.c \
	src/solid_color_view.c \
	src/stack_header_view.c \
	src/stack_view.c \
	src/stack_view_controller.c \
	src/subapp_cell.c \
	src/switch_view.c \
	src/tab_union_view_controller.c \
	src/tab_view.c \
	src/tab_view_cell.c \
	src/tab_view_controller.c \
	src/tab_view_data_source.c \
	src/table_size_1D_manager.c \
	src/table_view.c \
	src/table_view_data_source.c \
	src/table_view_with_frozen_header.c \
	src/text_area.c \
	src/text_cursor_view.c \
	src/text_input.c \
	src/text_input_helpers.c \
	src/text_view.c \
	src/timer.c \
	src/toggleable_dot_view.c \
	src/toggleable_view.c \
	src/toolbox.c \
	src/transparent_image_view.c \
	src/unequal_view.c \
	src/view.c \
	src/view_controller.c \
	src/warning_controller.c \
	src/window.c \
)
