# 自动生成的 ion 目录的源文件列表
# 生成时间: 2025-12-26 15:32:43
# 目录: ion
# 说明: 此文件由脚本自动生成，包含所有子目录中的.c文件（保留路径）

ION_SRCS := $(addprefix ion/, \
	src/device/shared/boot/rt0.c \
	src/device/shared/drivers/assert.c \
	src/device/shared/drivers/board_unprivileged.c \
	src/device/shared/drivers/console_display.c \
	src/device/shared/drivers/dfu_interfaces.c \
	src/device/shared/drivers/flash_information.c \
	src/device/shared/drivers/read_only_memory.c \
	src/device/shared/drivers/trampoline.c \
	src/device/shared/drivers/usb_unprivileged.c \
	src/device/shared/flash/board.c \
	src/device/shared/post_and_hardware_tests.c \
	src/device/shared/usb/calculator.c \
	src/device/shared/usb/calculator_userland_leave_reset.c \
	src/device/shared/usb/dfu_interface.c \
	src/device/shared/usb/dfu_xip.c \
	src/device/shared/usb/stack/descriptor/bos_descriptor.c \
	src/device/shared/usb/stack/descriptor/configuration_descriptor.c \
	src/device/shared/usb/stack/descriptor/descriptor.c \
	src/device/shared/usb/stack/descriptor/device_capability_descriptor.c \
	src/device/shared/usb/stack/descriptor/device_descriptor.c \
	src/device/shared/usb/stack/descriptor/dfu_functional_descriptor.c \
	src/device/shared/usb/stack/descriptor/extended_compat_id_descriptor.c \
	src/device/shared/usb/stack/descriptor/interface_descriptor.c \
	src/device/shared/usb/stack/descriptor/language_id_string_descriptor.c \
	src/device/shared/usb/stack/descriptor/microsoft_os_string_descriptor.c \
	src/device/shared/usb/stack/descriptor/platform_device_capability_descriptor.c \
	src/device/shared/usb/stack/descriptor/string_descriptor.c \
	src/device/shared/usb/stack/descriptor/url_descriptor.c \
	src/device/shared/usb/stack/descriptor/webusb_platform_descriptor.c \
	src/device/shared/usb/stack/device.c \
	src/device/shared/usb/stack/device_otg.c \
	src/device/shared/usb/stack/endpoint0_otg.c \
	src/device/shared/usb/stack/interface.c \
	src/device/shared/usb/stack/request_recipient.c \
	src/device/shared/usb/stack/setup_packet.c \
	src/device/shared/usb/stack/streamable.c \
	src/device/userland/boot/isr.c \
	src/device/userland/boot/rt0.c \
	src/device/userland/drivers/authentication.c \
	src/device/userland/drivers/backlight.c \
	src/device/userland/drivers/battery.c \
	src/device/userland/drivers/board.c \
	src/device/userland/drivers/board_dual_slots.c \
	src/device/userland/drivers/board_ram_dfu_xip.c \
	src/device/userland/drivers/circuit_breaker.c \
	src/device/userland/drivers/clipboard.c \
	src/device/userland/drivers/compilation_flags.c \
	src/device/userland/drivers/crc32.c \
	src/device/userland/drivers/device_name.c \
	src/device/userland/drivers/display.c \
	src/device/userland/drivers/events.c \
	src/device/userland/drivers/exam_bytes.c \
	src/device/userland/drivers/fcc_id.c \
	src/device/userland/drivers/flash_write_with_interruptions.c \
	src/device/userland/drivers/init.c \
	src/device/userland/drivers/keyboard.c \
	src/device/userland/drivers/led.c \
	src/device/userland/drivers/pcb_version.c \
	src/device/userland/drivers/persisting_bytes.c \
	src/device/userland/drivers/power.c \
	src/device/userland/drivers/random.c \
	src/device/userland/drivers/reset.c \
	src/device/userland/drivers/reset_svcall.c \
	src/device/userland/drivers/serial_number.c \
	src/device/userland/drivers/serial_number_svcall.c \
	src/device/userland/drivers/stack.c \
	src/device/userland/drivers/timing.c \
	src/device/userland/drivers/usb.c \
	src/device/userland/drivers/usb_svcall.c \
	src/device/userland/drivers/userland_header.c \
	src/shared/collect_registers.c \
	src/shared/console_line.c \
	src/shared/display_context.c \
	src/shared/dummy/external_apps.c \
	src/shared/exam_mode.c \
	src/shared/stack_position.c \
	src/shared/storage/file_system.c \
	src/shared/storage/record.c \
	src/shared/storage/record_name_verifier.c \
)
