# 自动生成的 liba 目录的源文件列表
# 生成时间: 2025-12-26 15:32:43
# 目录: liba
# 说明: 此文件由脚本自动生成，包含所有子目录中的.c文件（保留路径）

LIBA_SRCS := $(addprefix liba/, \
	src/abs.c \
	src/aeabi-rt/atexit.c \
	src/armv7m/longjmp.c \
	src/armv7m/setjmp.c \
	src/bzero.c \
	src/ctype.c \
	src/errno.c \
	src/external/openbsd/b_exp__D.c \
	src/external/openbsd/b_log__D.c \
	src/external/openbsd/b_tgamma.c \
	src/external/openbsd/e_acos.c \
	src/external/openbsd/e_acosf.c \
	src/external/openbsd/e_acosh.c \
	src/external/openbsd/e_acoshf.c \
	src/external/openbsd/e_asin.c \
	src/external/openbsd/e_asinf.c \
	src/external/openbsd/e_atan2.c \
	src/external/openbsd/e_atan2f.c \
	src/external/openbsd/e_atanh.c \
	src/external/openbsd/e_atanhf.c \
	src/external/openbsd/e_cosh.c \
	src/external/openbsd/e_coshf.c \
	src/external/openbsd/e_exp.c \
	src/external/openbsd/e_expf.c \
	src/external/openbsd/e_fmod.c \
	src/external/openbsd/e_fmodf.c \
	src/external/openbsd/e_hypot.c \
	src/external/openbsd/e_hypotf.c \
	src/external/openbsd/e_lgamma_r.c \
	src/external/openbsd/e_lgammaf_r.c \
	src/external/openbsd/e_log.c \
	src/external/openbsd/e_log10.c \
	src/external/openbsd/e_log10f.c \
	src/external/openbsd/e_log2.c \
	src/external/openbsd/e_logf.c \
	src/external/openbsd/e_pow.c \
	src/external/openbsd/e_powf.c \
	src/external/openbsd/e_rem_pio2.c \
	src/external/openbsd/e_rem_pio2f.c \
	src/external/openbsd/e_scalb.c \
	src/external/openbsd/e_sinh.c \
	src/external/openbsd/e_sinhf.c \
	src/external/openbsd/e_sqrt.c \
	src/external/openbsd/e_sqrtf.c \
	src/external/openbsd/k_cos.c \
	src/external/openbsd/k_cosf.c \
	src/external/openbsd/k_rem_pio2.c \
	src/external/openbsd/k_rem_pio2f.c \
	src/external/openbsd/k_sin.c \
	src/external/openbsd/k_sinf.c \
	src/external/openbsd/k_tan.c \
	src/external/openbsd/k_tanf.c \
	src/external/openbsd/s_asinh.c \
	src/external/openbsd/s_asinhf.c \
	src/external/openbsd/s_atan.c \
	src/external/openbsd/s_atanf.c \
	src/external/openbsd/s_ceil.c \
	src/external/openbsd/s_ceilf.c \
	src/external/openbsd/s_copysign.c \
	src/external/openbsd/s_copysignf.c \
	src/external/openbsd/s_cos.c \
	src/external/openbsd/s_cosf.c \
	src/external/openbsd/s_erf.c \
	src/external/openbsd/s_erff.c \
	src/external/openbsd/s_expm1.c \
	src/external/openbsd/s_expm1f.c \
	src/external/openbsd/s_fabs.c \
	src/external/openbsd/s_fabsf.c \
	src/external/openbsd/s_floor.c \
	src/external/openbsd/s_floorf.c \
	src/external/openbsd/s_fmax.c \
	src/external/openbsd/s_fmaxf.c \
	src/external/openbsd/s_frexp.c \
	src/external/openbsd/s_frexpf.c \
	src/external/openbsd/s_log1p.c \
	src/external/openbsd/s_log1pf.c \
	src/external/openbsd/s_logb.c \
	src/external/openbsd/s_logbf.c \
	src/external/openbsd/s_modf.c \
	src/external/openbsd/s_modff.c \
	src/external/openbsd/s_nextafter.c \
	src/external/openbsd/s_nextafterf.c \
	src/external/openbsd/s_rint.c \
	src/external/openbsd/s_round.c \
	src/external/openbsd/s_roundf.c \
	src/external/openbsd/s_scalbn.c \
	src/external/openbsd/s_scalbnf.c \
	src/external/openbsd/s_signgam.c \
	src/external/openbsd/s_sin.c \
	src/external/openbsd/s_sinf.c \
	src/external/openbsd/s_tan.c \
	src/external/openbsd/s_tanf.c \
	src/external/openbsd/s_tanh.c \
	src/external/openbsd/s_tanhf.c \
	src/external/openbsd/s_trunc.c \
	src/external/openbsd/s_truncf.c \
	src/external/openbsd/w_lgamma.c \
	src/external/openbsd/w_lgammaf.c \
	src/external/sqlite/mem5.c \
	src/fpclassify.c \
	src/fpclassifyf.c \
	src/ieee754.c \
	src/malloc.c \
	src/nearbyint.c \
	src/nearbyintf.c \
)
