# 自动生成的 poincare 目录的源文件列表
# 生成时间: 2025-12-26 15:32:44
# 目录: poincare
# 说明: 此文件由脚本自动生成，包含所有子目录中的.c文件（保留路径）

POINCARE_SRCS := $(addprefix poincare/, \
	src/additional_results_helper.c \
	src/circuit_breaker_checkpoint.c \
	src/comparison_operator.c \
	src/context.c \
	src/empty_context.c \
	src/exception_checkpoint.c \
	src/expression/advanced_operation.c \
	src/expression/advanced_reduction.c \
	src/expression/algebraic.c \
	src/expression/aliases.c \
	src/expression/approximation.c \
	src/expression/approximation_derivative.c \
	src/expression/approximation_helpers.c \
	src/expression/approximation_integral.c \
	src/expression/approximation_logarithm.c \
	src/expression/approximation_matrix.c \
	src/expression/approximation_power.c \
	src/expression/approximation_prepare.c \
	src/expression/approximation_trigonometry.c \
	src/expression/arithmetic.c \
	src/expression/beautification.c \
	src/expression/binary.c \
	src/expression/bounds.c \
	src/expression/builtin.c \
	src/expression/cas_disabled.c \
	src/expression/continuity.c \
	src/expression/decimal.c \
	src/expression/degree.c \
	src/expression/dependency.c \
	src/expression/derivation.c \
	src/expression/dimension.c \
	src/expression/division.c \
	src/expression/equal_sign.c \
	src/expression/equation_solver.c \
	src/expression/expression_or_float.c \
	src/expression/float_helper.c \
	src/expression/infinity.c \
	src/expression/integer.c \
	src/expression/integer_serialization.c \
	src/expression/integration.c \
	src/expression/list.c \
	src/expression/logarithm.c \
	src/expression/matrix.c \
	src/expression/metric.c \
	src/expression/number.c \
	src/expression/order.c \
	src/expression/parametric.c \
	src/expression/physical_constant.c \
	src/expression/polynomial.c \
	src/expression/power_like.c \
	src/expression/projection.c \
	src/expression/random.c \
	src/expression/rational.c \
	src/expression/sequence.c \
	src/expression/set.c \
	src/expression/simplification.c \
	src/expression/symbol.c \
	src/expression/systematic_addition.c \
	src/expression/systematic_multiplication.c \
	src/expression/systematic_operation.c \
	src/expression/systematic_reduction.c \
	src/expression/trigonometry.c \
	src/expression/trigonometry_exact_formulas.c \
	src/expression/undefined.c \
	src/expression/units/representatives.c \
	src/expression/units/unit.c \
	src/expression/variables.c \
	src/expression/vector.c \
	src/float_list.c \
	src/function_properties/conic.c \
	src/function_properties/function_type.c \
	src/function_properties/helper.c \
	src/function_properties/integral.c \
	src/helpers/cas.c \
	src/helpers/expression_equal_sign.c \
	src/helpers/layout.c \
	src/helpers/scatter_plot_iterable.c \
	src/helpers/sequence.c \
	src/helpers/store.c \
	src/helpers/symbol.c \
	src/helpers/trigonometry.c \
	src/init.c \
	src/layout/autocompleted_pair.c \
	src/layout/code_point_layout.c \
	src/layout/cursor_motion.c \
	src/layout/empty_rectangle.c \
	src/layout/grid.c \
	src/layout/input_beautification.c \
	src/layout/layout_cursor.c \
	src/layout/layout_memoization.c \
	src/layout/layout_selection.c \
	src/layout/layout_serializer.c \
	src/layout/layout_span.c \
	src/layout/layout_span_decoder.c \
	src/layout/layouter.c \
	src/layout/multiplication_symbol.c \
	src/layout/parser.c \
	src/layout/parsing/helper.c \
	src/layout/parsing/latex_parser.c \
	src/layout/parsing/rack_parser.c \
	src/layout/parsing/tokenizer.c \
	src/layout/rack_from_text.c \
	src/layout/rack_layout.c \
	src/layout/rack_layout_decoder.c \
	src/layout/render.c \
	src/layout/xnt.c \
	src/memory/block_stack.c \
	src/memory/n_ary.c \
	src/memory/pattern_matching.c \
	src/memory/tree.c \
	src/memory/tree_ref.c \
	src/memory/tree_stack.c \
	src/memory/tree_stack_checkpoint.c \
	src/memory/value_block.c \
	src/memory/visualization.c \
	src/pool.c \
	src/pool/expression.c \
	src/pool/layout.c \
	src/pool/pool_layout_cursor.c \
	src/pool_checkpoint.c \
	src/pool_handle.c \
	src/pool_object.c \
	src/pool_variable_context.c \
	src/preferences.c \
	src/preferences_in_storage.c \
	src/print.c \
	src/print_float.c \
	src/random.c \
	src/range.c \
	src/sign.c \
	src/solver/beta_function.c \
	src/solver/erf_inv.c \
	src/solver/matrix_array.c \
	src/solver/point_of_interest_list.c \
	src/solver/regularized_gamma_function.c \
	src/solver/regularized_incomplete_beta_function.c \
	src/solver/roots.c \
	src/solver/solver.c \
	src/solver/solver_algorithms.c \
	src/solver/zoom.c \
	src/statistics/data_table.c \
	src/statistics/distributions/distribution.c \
	src/statistics/distributions/distribution_cumulative_function.c \
	src/statistics/distributions/distribution_cumulative_inverse.c \
	src/statistics/distributions/distribution_evaluate.c \
	src/statistics/distributions/distribution_method.c \
	src/statistics/distributions/distribution_parameters.c \
	src/statistics/domain.c \
	src/statistics/inference/chi2_test.c \
	src/statistics/inference/confidence_interval.c \
	src/statistics/inference/inference.c \
	src/statistics/inference/significance_test.c \
	src/statistics/regression/affine_regression.c \
	src/statistics/regression/cubic_regression.c \
	src/statistics/regression/exponential_regression.c \
	src/statistics/regression/linear_regression.c \
	src/statistics/regression/logarithmic_regression.c \
	src/statistics/regression/logistic_regression.c \
	src/statistics/regression/median_regression.c \
	src/statistics/regression/power_regression.c \
	src/statistics/regression/proportional_regression.c \
	src/statistics/regression/quadratic_regression.c \
	src/statistics/regression/quartic_regression.c \
	src/statistics/regression/regression.c \
	src/statistics/regression/regression_switch.c \
	src/statistics/regression/transformed_regression.c \
	src/statistics/regression/trigonometric_regression.c \
	src/statistics/statistics_dataset.c \
	src/statistics/statistics_dataset_column.c \
	src/tree_variable_context.c \
	src/trigonometry.c \
)
