// This file is auto-generated by Inliner. Do not edit manually.
#ifndef IMAGE_STORE_CARET_H
#define IMAGE_STORE_CARET_H

#include <escher/image.h>

namespace ImageStore {

extern const Escher::Image * const Caret;

};

#endif
