/* This file is auto-generated by the rasterizer */

#include <kandinsky/font.h>

constexpr static KDFont::CodePointIndexPair table[] = {
  KDFont::CodePointIndexPair(0x20, 0),
  KDFont::CodePointIndexPair(0xaa, 95),
  KDFont::CodePointIndexPair(0xb0, 96),
  KDFont::CodePointIndexPair(0xb7, 98),
  KDFont::CodePointIndexPair(0xba, 99),
  KDFont::CodePointIndexPair(0xc6, 100),
  KDFont::CodePointIndexPair(0xd0, 101),
  KDFont::CodePointIndexPair(0xd7, 102),
  KDFont::CodePointIndexPair(0xde, 104),
  KDFont::CodePointIndexPair(0xe6, 106),
  KDFont::CodePointIndexPair(0xf0, 107),
  KDFont::CodePointIndexPair(0xf7, 108),
  KDFont::CodePointIndexPair(0xfe, 110),
  KDFont::CodePointIndexPair(0x300, 111),
  KDFont::CodePointIndexPair(0x305, 115),
  KDFont::CodePointIndexPair(0x308, 116),
  KDFont::CodePointIndexPair(0x30a, 117),
  KDFont::CodePointIndexPair(0x327, 118),
  KDFont::CodePointIndexPair(0x338, 119),
  KDFont::CodePointIndexPair(0x393, 120),
  KDFont::CodePointIndexPair(0x3a3, 122),
  KDFont::CodePointIndexPair(0x3a9, 123),
  KDFont::CodePointIndexPair(0x3b1, 124),
  KDFont::CodePointIndexPair(0x3bb, 132),
  KDFont::CodePointIndexPair(0x3c0, 134),
  KDFont::CodePointIndexPair(0x3c3, 136),
  KDFont::CodePointIndexPair(0x3c7, 137),
  KDFont::CodePointIndexPair(0x3c9, 138),
  KDFont::CodePointIndexPair(0x1d07, 139),
  KDFont::CodePointIndexPair(0x2192, 140),
  KDFont::CodePointIndexPair(0x2197, 141),
  KDFont::CodePointIndexPair(0x2211, 143),
  KDFont::CodePointIndexPair(0x221a, 144),
  KDFont::CodePointIndexPair(0x221e, 145),
  KDFont::CodePointIndexPair(0x222b, 146),
  KDFont::CodePointIndexPair(0x2248, 147),
  KDFont::CodePointIndexPair(0x2264, 148),
  KDFont::CodePointIndexPair(0x22a6, 150),
  KDFont::CodePointIndexPair(0x27e8, 151),
  KDFont::CodePointIndexPair(0xfffd, 153),
};

const KDFont::CodePointIndexPair * KDFont::s_CodePointToGlyphIndex = table;
const size_t KDFont::s_codePointPairsTableLength = 40;

