// This file is auto-generated by apps_layout.py

#include "apps_layout.h"
#include <apps/country_preferences.h>
#include <apps/global_preferences.h>
#include <assert.h>

namespace Home {

/* Permutations are built so that Permutation[n] is the index of the snapshot
 * for the nth app in the Home menu. */

constexpr static int DefaultAppsPermutation[] = {
  0,
  1,
  2,
  3,
  4,
  5,
  7,
  8,
  9,
  10,
  6,
  11,
  12,
};
static_assert(DefaultAppsPermutation[0] == 0, "The Home apps must always be at index 0");

constexpr static int Variant1AppsPermutation[] = {
  0,
  1,
  2,
  7,
  4,
  9,
  5,
  6,
  8,
  3,
  10,
  11,
  12,
};
static_assert(Variant1AppsPermutation[0] == 0, "The Home apps must always be at index 0");

constexpr static int Variant2AppsPermutation[] = {
  0,
  1,
  2,
  7,
  9,
  8,
  5,
  4,
  3,
  10,
  6,
  11,
  12,
};
static_assert(Variant2AppsPermutation[0] == 0, "The Home apps must always be at index 0");

constexpr static int Variant3AppsPermutation[] = {
  0,
  1,
  2,
  7,
  4,
  5,
  8,
  9,
  6,
  11,
  10,
  3,
  12,
};
static_assert(Variant3AppsPermutation[0] == 0, "The Home apps must always be at index 0");

constexpr static int Variant4AppsPermutation[] = {
  0,
  1,
  2,
  7,
  4,
  9,
  8,
  5,
  6,
  11,
  10,
  3,
  12,
};
static_assert(Variant4AppsPermutation[0] == 0, "The Home apps must always be at index 0");

int PermutedAppSnapshotIndex(int index) {
  CountryPreferences::HomeAppsLayout currentLayout = GlobalPreferences::SharedGlobalPreferences()->homeAppsLayout();
  if (currentLayout == CountryPreferences::HomeAppsLayout::Default) {
    return DefaultAppsPermutation[index];  }
  if (currentLayout == CountryPreferences::HomeAppsLayout::Variant1) {
    return Variant1AppsPermutation[index];  }
  if (currentLayout == CountryPreferences::HomeAppsLayout::Variant2) {
    return Variant2AppsPermutation[index];  }
  if (currentLayout == CountryPreferences::HomeAppsLayout::Variant3) {
    return Variant3AppsPermutation[index];  }
  if (currentLayout == CountryPreferences::HomeAppsLayout::Variant4) {
    return Variant4AppsPermutation[index];  }
  assert(false);
  return -1;
}

}

