set(escher)

# 源文件列表（支持通配符或明确列表）
set(MODULE_SOURCES
        image/caret.cpp
        src/abstract_text_field.cpp
        src/alternate_empty_nested_menu_controller.cpp
        src/alternate_empty_view_controller.cpp
        src/alternate_view_controller.cpp
        src/app.cpp
        src/bank_view_controller.cpp
        src/blink_timer.cpp
        src/bordered.cpp
        src/bordering_view.cpp
        src/buffer_text_view.cpp
        src/button_cell.cpp
        src/button_row_controller.cpp
        src/button_state.cpp
        src/chained_text_field_delegate.cpp
        src/chevron_view.cpp
        src/clipboard.cpp
        src/container.cpp
        src/dropdown_view.cpp
        src/editable_expression_cell.cpp
        src/editable_expression_model_cell.cpp
        src/editable_field.cpp
        src/editable_text_cell.cpp
        src/ellipsis_view.cpp
        src/even_odd_buffer_text_cell.cpp
        src/even_odd_cell.cpp
        src/even_odd_cell_with_ellipsis.cpp
        src/even_odd_editable_text_cell.cpp
        src/even_odd_expression_cell.cpp
        src/even_odd_message_text_cell.cpp
        src/explicit_list_view_data_source.cpp
        src/expression_input_bar.cpp
        src/gauge_view.cpp
        src/glyphs_view.cpp
        src/heavy_table_size_manager.cpp
        src/highlight_cell.cpp
        src/highlight_image_cell.cpp
        src/horizontal_or_vertical_layout.cpp
        src/image_view.cpp
        src/init.cpp
        src/input_view_controller.cpp
        src/invocation.cpp
        src/key_view.cpp
        src/layout_field.cpp
        src/layout_view.cpp
        src/list_view_data_source.cpp
        src/list_with_top_and_bottom_controller.cpp
        src/menu_cell.cpp
        src/menu_cell_with_editable_text.cpp
        src/message_text_view.cpp
        src/message_view.cpp
        src/modal_view_controller.cpp
        src/modal_view_empty_controller.cpp
        src/nested_menu_controller.cpp
        src/palette.cpp
        src/pointer_text_view.cpp
        src/pop_up_controller.cpp
        src/preface_data_source.cpp
        src/prefaced_table_view.cpp
        src/prefaced_twice_table_view.cpp
        src/responder.cpp
        src/run_loop.cpp
        src/scroll_view.cpp
        src/scroll_view_data_source.cpp
        src/scroll_view_indicator.cpp
        src/scrollable_layout_view.cpp
        src/scrollable_multiple_layouts_view.cpp
        src/scrollable_two_layouts_cell.cpp
        src/scrollable_view.cpp
        src/selectable_list_view.cpp
        src/selectable_list_view_controller.cpp
        src/selectable_list_view_delegate.cpp
        src/selectable_table_view.cpp
        src/selectable_table_view_delegate.cpp
        src/solid_color_view.cpp
        src/stack_header_view.cpp
        src/stack_view.cpp
        src/stack_view_controller.cpp
        src/subapp_cell.cpp
        src/switch_view.cpp
        src/tab_union_view_controller.cpp
        src/tab_view.cpp
        src/tab_view_cell.cpp
        src/tab_view_controller.cpp
        src/tab_view_data_source.cpp
        src/table_size_1D_manager.cpp
        src/table_view.cpp
        src/table_view_data_source.cpp
        src/table_view_with_frozen_header.cpp
        src/text_area.cpp
        src/text_cursor_view.cpp
        src/text_input.cpp
        src/text_input_helpers.cpp
        src/text_view.cpp
        src/timer.cpp
        src/toggleable_dot_view.cpp
        src/toggleable_view.cpp
        src/toolbox.cpp
        src/transparent_image_view.cpp
        src/unequal_view.cpp
        src/view.cpp
        src/view_controller.cpp
        src/warning_controller.cpp
        src/window.cpp
        )

# 注册为IDF组件
idf_component_register(
        SRCS ${MODULE_SOURCES}
        INCLUDE_DIRS "include"
            ${CMAKE_CURRENT_SOURCE_DIR}/..
            ${CMAKE_CURRENT_LIST_DIR}/include  # 绝对路径
            ${CMAKE_CURRENT_SOURCE_DIR}/../kandinsky/include
            ${CMAKE_CURRENT_SOURCE_DIR}/../ion/include
            ${CMAKE_CURRENT_SOURCE_DIR}/../ion/include/ion/keyboard/epsilon
            ${CMAKE_CURRENT_SOURCE_DIR}/../omg/include
            ${CMAKE_CURRENT_SOURCE_DIR}/../poincare/include
       REQUIRES
            omg
            ion
            poincare
            kandinsky
)
