cmake_minimum_required(VERSION 3.10)
project(apps CXX)  # 指定为 C 项目

set(COMPONENT_NAME apps)

# 源文件列表（支持通配符或明确列表）
set(MODULE_SOURCES
        apps_container.cpp
        apps_container_helper.cpp
        apps_container_launch_default.cpp
        apps_container_prompt_none.cpp
        apps_container_storage.cpp
        apps_window.cpp
        backlight_dimming_timer.cpp
        battery_timer.cpp
        battery_view.cpp
        calculation/additional_results/additional_results_controller.cpp
        calculation/additional_results/additional_results_type.cpp
        calculation/additional_results/chained_expressions_list_controller.cpp
        calculation/additional_results/complex_graph_cell.cpp
        calculation/additional_results/complex_list_controller.cpp
        calculation/additional_results/complex_model.cpp
        calculation/additional_results/expressions_list_controller.cpp
        calculation/additional_results/function_graph_cell.cpp
        calculation/additional_results/function_list_controller.cpp
        calculation/additional_results/function_model.cpp
        calculation/additional_results/illustrated_expressions_list_controller.cpp
        calculation/additional_results/illustration_cell.cpp
        calculation/additional_results/integer_list_controller.cpp
        calculation/additional_results/layout_with_equal_sign_view.cpp
        calculation/additional_results/matrix_list_controller.cpp
        calculation/additional_results/rational_list_controller.cpp
        calculation/additional_results/scientific_notation_list_controller.cpp
        calculation/additional_results/scrollable_three_layouts_view.cpp
        calculation/additional_results/trigonometry_graph_cell.cpp
        calculation/additional_results/trigonometry_list_controller.cpp
        calculation/additional_results/trigonometry_model.cpp
        calculation/additional_results/unit_comparison_helper.cpp
        calculation/additional_results/unit_list_controller.cpp
        calculation/additional_results/vector_graph_cell.cpp
        calculation/additional_results/vector_helper.cpp
        calculation/additional_results/vector_list_controller.cpp
        calculation/additional_results/vector_model.cpp
        calculation/app.cpp
        calculation/calculation.cpp
        calculation/calculation_icon.cpp
        calculation/calculation_selectable_list_view.cpp
        calculation/calculation_store.cpp
        calculation/edit_expression_controller.cpp
        calculation/history_controller.cpp
        calculation/history_view_cell.cpp
        calculation/layout_field.cpp
        code/app.cpp
        code/clipboard.cpp
        code/code_icon.cpp
        code/console_controller.cpp
        code/console_edit_cell.cpp
        code/console_line_cell.cpp
        code/console_store.cpp
        code/editor_controller.cpp
        code/editor_view.cpp
        code/helpers.cpp
        code/menu_controller.cpp
        code/python_text_area.cpp
        code/python_toolbox_controller.cpp
        code/python_variable_box_controller.cpp
        code/sandbox_controller.cpp
        code/script.cpp
        code/script_name_cell.cpp
        code/script_parameter_controller.cpp
        code/script_store.cpp
        code/script_template.cpp
        code/subtitle_cell.cpp
        distributions/app.cpp
        distributions/controllers/calculation_cell.cpp
        distributions/controllers/calculation_controller.cpp
        distributions/controllers/calculation_popup_data_source.cpp
        distributions/controllers/distribution_controller.cpp
        distributions/controllers/distribution_curve_view.cpp
        distributions/controllers/parameters_controller.cpp
        distributions/distributions_icon.cpp
        distributions/images/binomial_icon.cpp
        distributions/images/calculation1_icon.cpp
        distributions/images/calculation2_icon.cpp
        distributions/images/calculation3_icon.cpp
        distributions/images/calculation4_icon.cpp
        distributions/images/chi_squared_icon.cpp
        distributions/images/exponential_icon.cpp
        distributions/images/fisher_icon.cpp
        distributions/images/geometric_icon.cpp
        distributions/images/hypergeometric_icon.cpp
        distributions/images/normal_icon.cpp
        distributions/images/poisson_icon.cpp
        distributions/images/student_icon.cpp
        distributions/images/uniform_icon.cpp
        distributions/models/calculation/calculation.cpp
        distributions/models/calculation/discrete_calculation.cpp
        distributions/models/calculation/finite_integral_calculation.cpp
        distributions/models/calculation/left_integral_calculation.cpp
        distributions/models/calculation/right_integral_calculation.cpp
        distributions/models/distribution/binomial_distribution.cpp
        distributions/models/distribution/chi_squared_distribution.cpp
        distributions/models/distribution/distribution.cpp
        distributions/models/distribution/exponential_distribution.cpp
        distributions/models/distribution/fisher_distribution.cpp
        distributions/models/distribution/hypergeometric_distribution.cpp
        distributions/models/distribution/normal_distribution.cpp
        distributions/models/distribution/poisson_distribution.cpp
        distributions/models/distribution/student_distribution.cpp
        distributions/models/distribution/uniform_distribution.cpp
        elements/app.cpp
        elements/banner_view.cpp
        elements/data_field.cpp
        elements/details_list_controller.cpp
        elements/display_type_controller.cpp
        elements/elements_data_base.cpp
        elements/elements_icon.cpp
        elements/elements_view.cpp
        elements/elements_view_data_source.cpp
        elements/main_controller.cpp
        elements/single_element_view.cpp
        elements/suggestion_text_field.cpp
        elements/table_layout.cpp
        empty_battery_window.cpp
        exam_icon.cpp
        exam_pop_up_controller.cpp
        external/simulator.cpp
        #external/sample_c/src/sample_c_main.c
        #external/sample_c/src/sample_c_icon.cpp
        #external/sample_cpp/src/alien.cpp
        #external/sample_cpp/src/life.cpp
        #external/sample_cpp/src/sample_cpp_main.cpp
        #external/sample_cpp/src/rocket.cpp
        #external/sample_cpp/src/spaceship.cpp
        #external/sample_cpp/src/score.cpp
        #external/sample_cpp/src/sample_cpp_icon.cpp
        #external/rpn_cpp/src/converter.cpp
        #external/rpn_cpp/src/input_field.cpp
        #external/rpn_cpp/src/rpn_main.cpp
        external/rpn_cpp/src/rpn_icon.cpp
        #external/rpn_cpp/src/store.cpp
        #external/rpn_cpp/src/view.cpp
        external/khicas/khicas_main.cpp
        external/khicas/khicas_icon.cpp
        build_in_external_apps.cpp
        finance/app.cpp
        finance/data.cpp
        finance/finance_icon.cpp
        finance/interest_menu_controller.cpp
        finance/menu_controller.cpp
        finance/parameters_controller.cpp
        finance/result_controller.cpp
        global_preferences.cpp
        graph/app.cpp
        graph/graph/area_between_curves_graph_controller.cpp
        graph/graph/area_between_curves_parameter_controller.cpp
        graph/graph/banner_view.cpp
        graph/graph/calculation_graph_controller.cpp
        graph/graph/calculation_parameter_controller.cpp
        graph/graph/curve_parameter_controller.cpp
        graph/graph/extremum_graph_controller.cpp
        graph/graph/graph_controller.cpp
        graph/graph/graph_controller_helper.cpp
        graph/graph/graph_view.cpp
        graph/graph/integral_graph_controller.cpp
        graph/graph/interest_view.cpp
        graph/graph/intersection_graph_controller.cpp
        graph/graph/points_of_interest_cache.cpp
        graph/graph/preimage_graph_controller.cpp
        graph/graph/preimage_parameter_controller.cpp
        graph/graph/root_graph_controller.cpp
        graph/graph/tangent_graph_controller.cpp
        graph/graph_icon.cpp
        graph/list/editable_function_cell.cpp
        graph/list/function_cell.cpp
        graph/list/function_models_parameter_controller.cpp
        graph/list/list_controller.cpp
        graph/shared/derivative_column_parameter_controller.cpp
        graph/shared/derivatives_parameter_controller.cpp
        graph/shared/details_parameter_controller.cpp
        graph/shared/domain_parameter_controller.cpp
        graph/shared/function_parameter_controller.cpp
        graph/values/interval_parameter_selector_controller.cpp
        graph/values/values_controller.cpp
        hardware_test/app.cpp
        hardware_test/arrow_view.cpp
        hardware_test/battery_test_controller.cpp
        hardware_test/code_128b_view.cpp
        hardware_test/colors_lcd_test_controller.cpp
        hardware_test/dead_pixels_test_controller.cpp
        hardware_test/keyboard_model.cpp
        hardware_test/keyboard_test_controller.cpp
        hardware_test/keyboard_view.cpp
        hardware_test/lcd_data_test_controller.cpp
        hardware_test/lcd_timing_test_controller.cpp
        hardware_test/led_test_controller.cpp
        hardware_test/serial_number_controller.cpp
        hardware_test/vblank_test_controller.cpp
        home/app.cpp
        home/app_cell.cpp
        home/apps_layout.cpp
        home/controller.cpp
        i18n.cpp
        inference/app.cpp
        inference/controllers/categorical_cell.cpp
        inference/controllers/categorical_controller.cpp
        inference/controllers/categorical_table_cell.cpp
        inference/controllers/chi_square/categorical_type_controller.cpp
        inference/controllers/chi_square/homogeneity_data_source.cpp
        inference/controllers/chi_square/input_goodness_controller.cpp
        inference/controllers/chi_square/input_goodness_table_cell.cpp
        inference/controllers/chi_square/input_homogeneity_controller.cpp
        inference/controllers/chi_square/input_homogeneity_table_cell.cpp
        inference/controllers/chi_square/results_goodness_controller.cpp
        inference/controllers/chi_square/results_goodness_table_cell.cpp
        inference/controllers/chi_square/results_homogeneity_controller.cpp
        inference/controllers/chi_square/results_homogeneity_table_cell.cpp
        inference/controllers/comparison_operator_popup_data_source.cpp
        inference/controllers/confidence_interval/interval_conclusion_view.cpp
        inference/controllers/confidence_interval/interval_curve_view.cpp
        inference/controllers/confidence_interval/interval_graph_controller.cpp
        inference/controllers/confidence_interval/interval_graph_view.cpp
        inference/controllers/dataset_controller.cpp
        inference/controllers/dynamic_cells_data_source.cpp
        inference/controllers/input_controller.cpp
        inference/controllers/results_controller.cpp
        inference/controllers/significance_test/hypothesis_controller.cpp
        inference/controllers/significance_test/legend_view.cpp
        inference/controllers/significance_test/test_curve_view.cpp
        inference/controllers/significance_test/test_graph_controller.cpp
        inference/controllers/significance_test/test_graph_view.cpp
        inference/controllers/significance_test/zoom_hint_view.cpp
        inference/controllers/store/input_store_controller.cpp
        inference/controllers/store/store_table_cell.cpp
        inference/controllers/test_controller.cpp
        inference/controllers/type_controller.cpp
        inference/images/confidence_interval.cpp
        inference/images/significance_test.cpp
        inference/inference_icon.cpp
        inference/models/chi2_test.cpp
        inference/models/confidence_interval.cpp
        inference/models/goodness_test.cpp
        inference/models/homogeneity_test.cpp
        inference/models/inference_model.cpp
        inference/models/input_table.cpp
        inference/models/input_table_from_store.cpp
        inference/models/one_mean_statistic.cpp
        inference/models/significance_test.cpp
        inference/models/slope_t_statistic.cpp
        inference/models/two_means_statistic.cpp
        init.cpp
        lock_view.cpp
        main.cpp
        on_boarding/app.cpp
        on_boarding/localization_controller.cpp
        on_boarding/startup_prompt_controller.cpp
        regression/app.cpp
        regression/data/store_controller.cpp
        regression/data/store_parameter_controller.cpp
        regression/graph/banner_view.cpp
        regression/graph/go_to_parameter_controller.cpp
        regression/graph/graph_controller.cpp
        regression/graph/graph_options_controller.cpp
        regression/graph/graph_view.cpp
        regression/graph/regression_controller.cpp
        regression/graph/residual_plot_controller.cpp
        regression/graph/residual_plot_curve_view.cpp
        regression/graph/residual_plot_range.cpp
        regression/model.cpp
        regression/regression_icon.cpp
        regression/stats/calculation_controller.cpp
        regression/stats/column_title_cell.cpp
        regression/stats/even_odd_double_buffer_text_cell.cpp
        regression/store.cpp
        sequence/app.cpp
        sequence/graph/cobweb_controller.cpp
        sequence/graph/cobweb_graph_view.cpp
        sequence/graph/curve_parameter_controller.cpp
        sequence/graph/curve_view_range.cpp
        sequence/graph/go_to_parameter_controller.cpp
        sequence/graph/graph_controller.cpp
        sequence/graph/graph_view.cpp
        sequence/graph/term_sum_controller.cpp
        sequence/list/editable_sequence_cell.cpp
        sequence/list/list_controller.cpp
        sequence/list/list_parameter_controller.cpp
        sequence/list/sequence_cell.cpp
        sequence/list/sequence_toolbox_data_source.cpp
        sequence/list/type_parameter_controller.cpp
        sequence/sequence_icon.cpp
        sequence/values/interval_parameter_controller.cpp
        sequence/values/sequence_column_parameter_controller.cpp
        sequence/values/sum_column_parameter_controller.cpp
        sequence/values/values_controller.cpp
        settings/app.cpp
        settings/main_controller.cpp
        settings/main_controller_prompt_none.cpp
        settings/settings_icon.cpp
        settings/sub_menu/about_controller.cpp
        settings/sub_menu/display_mode_controller.cpp
        settings/sub_menu/exam_mode_controller.cpp
        settings/sub_menu/generic_sub_controller.cpp
        settings/sub_menu/localization_controller.cpp
        settings/sub_menu/preferences_controller.cpp
        settings/sub_menu/press_to_test_controller.cpp
        settings/sub_menu/press_to_test_success.cpp
        settings/sub_menu/screen_timeout_controller.cpp
        settings/sub_menu/selectable_view_with_messages.cpp
        settings/sub_menu/test_mode_controller.cpp
        shared/app_with_store_menu.cpp
        shared/banner_view.cpp
        shared/buffer_function_title_cell.cpp
        shared/color_cell.cpp
        shared/color_names.cpp
        shared/color_parameter_controller.cpp
        shared/column_helper.cpp
        shared/column_parameter_controller.cpp
        shared/continuous_function.cpp
        shared/continuous_function_cache.cpp
        shared/continuous_function_properties.cpp
        shared/continuous_function_store.cpp
        shared/curve_selection_controller.cpp
        shared/curve_view_cursor.cpp
        shared/curve_view_range.cpp
        shared/dots.cpp
        shared/double_pair_store.cpp
        shared/double_pair_table_controller.cpp
        shared/editable_cell_table_view_controller.cpp
        shared/explicit_float_parameter_controller.cpp
        shared/expression_function_title_cell.cpp
        shared/expression_model.cpp
        shared/expression_model_handle.cpp
        shared/expression_model_list_controller.cpp
        shared/expression_model_store.cpp
        shared/expression_parameter_controller.cpp
        shared/float_parameter_controller.cpp
        shared/formula_template_menu_controller.cpp
        shared/function.cpp
        shared/function_app.cpp
        shared/function_banner_delegate.cpp
        shared/function_go_to_parameter_controller.cpp
        shared/function_graph_controller.cpp
        shared/function_graph_view.cpp
        shared/function_list_controller.cpp
        shared/function_name_helper.cpp
        shared/function_title_cell.cpp
        shared/function_zoom_and_pan_curve_view_controller.cpp
        shared/global_context.cpp
        shared/go_to_parameter_controller.cpp
        shared/grid_type_controller.cpp
        shared/images/cartesian_grid_icon.cpp
        shared/images/polar_grid_icon.cpp
        shared/interactive_curve_view_controller.cpp
        shared/interactive_curve_view_range.cpp
        shared/interactive_curve_view_range_delegate.cpp
        shared/interval.cpp
        shared/interval_parameter_controller.cpp
        shared/linear_regression_store.cpp
        shared/list_parameter_controller.cpp
        shared/localization_controller.cpp
        shared/math_field_delegate.cpp
        shared/math_toolbox_content.cpp
        shared/math_toolbox_controller.cpp
        shared/math_variable_box_controller.cpp
        shared/memoized_cursor_view.cpp
        shared/memoized_curve_view_range.cpp
        shared/menu_controller.cpp
        shared/ok_view.cpp
        shared/packed_range_1D.cpp
        shared/parameter_text_field_delegate.cpp
        shared/parameters_with_validation_controller.cpp
        shared/plot_view.cpp
        shared/plot_view_axes.cpp
        shared/plot_view_banners.cpp
        shared/plot_view_cursors.cpp
        shared/plot_view_plots.cpp
        shared/prompt_controller.cpp
        shared/range_parameter_controller.cpp
        shared/round_cursor_view.cpp
        shared/sequence.cpp
        shared/sequence_cache.cpp
        shared/sequence_context.cpp
        shared/sequence_store.cpp
        shared/shared_app.cpp
        shared/simple_interactive_curve_view_controller.cpp
        shared/single_interactive_curve_view_range_controller.cpp
        shared/single_range_controller.cpp
        shared/statistical_distribution.cpp
        shared/statistics_store.cpp
        shared/store_app.cpp
        shared/store_controller.cpp
        shared/store_menu_controller.cpp
        shared/store_parameter_controller.cpp
        shared/sum_graph_controller.cpp
        shared/tab_table_controller.cpp
        shared/toolbox_helpers.cpp
        shared/values_controller.cpp
        shared/values_parameter_controller.cpp
        shared/vertical_cursor_view.cpp
        shared/zoom_and_pan_curve_view_controller.cpp
        shared/zoom_curve_view_controller.cpp
        shift_alpha_lock_view.cpp
        solver/app.cpp
        solver/equation.cpp
        solver/equation_list_view.cpp
        solver/equation_models_parameter_controller.cpp
        solver/equation_store.cpp
        solver/interval_controller.cpp
        solver/list_controller.cpp
        solver/solutions_controller.cpp
        solver/solver_icon.cpp
        solver/system_of_equations.cpp
        statistics/app.cpp
        statistics/box_icon.cpp
        statistics/cumulative_icon.cpp
        statistics/data/store_controller.cpp
        statistics/data/store_parameter_controller.cpp
        statistics/graph/box_banner_view.cpp
        statistics/graph/box_controller.cpp
        statistics/graph/box_parameter_controller.cpp
        statistics/graph/box_range.cpp
        statistics/graph/box_view.cpp
        statistics/graph/chevrons.cpp
        statistics/graph/data_view.cpp
        statistics/graph/data_view_controller.cpp
        statistics/graph/frequency_controller.cpp
        statistics/graph/graph_type_controller.cpp
        statistics/graph/graph_view_model.cpp
        statistics/graph/histogram_banner_view.cpp
        statistics/graph/histogram_cell.cpp
        statistics/graph/histogram_list_controller.cpp
        statistics/graph/histogram_main_controller.cpp
        statistics/graph/histogram_main_view.cpp
        statistics/graph/histogram_parameter_controller.cpp
        statistics/graph/histogram_range.cpp
        statistics/graph/histogram_view.cpp
        statistics/graph/multiple_boxes_view.cpp
        statistics/graph/multiple_data_view.cpp
        statistics/graph/normal_probability_controller.cpp
        statistics/graph/plot_banner_view.cpp
        statistics/graph/plot_controller.cpp
        statistics/graph/plot_curve_view.cpp
        statistics/graph/plot_range.cpp
        statistics/graph/plot_view.cpp
        statistics/histogram_icon.cpp
        statistics/stat_icon.cpp
        statistics/statistics_normal_icon.cpp
        statistics/stats/calculation_controller.cpp
        statistics/stats/calculation_selectable_table_view.cpp
        statistics/store.cpp
        suspend_timer.cpp
        title_bar_view.cpp
        usb/app.cpp
        usb/usb_connected_controller.cpp
        )
# 创建静态库
add_library(${COMPONENT_NAME} STATIC
        ${MODULE_SOURCES}
)

# 设置包含目录
target_include_directories(${COMPONENT_NAME}
        PUBLIC
        ${CMAKE_CURRENT_LIST_DIR}
        ${CMAKE_CURRENT_LIST_DIR}/..
        ${CMAKE_CURRENT_SOURCE_DIR}/../escher/include
        ${CMAKE_CURRENT_SOURCE_DIR}/../ion/include
        ${CMAKE_CURRENT_SOURCE_DIR}/../ion/include/ion/keyboard/epsilon
        ${CMAKE_CURRENT_SOURCE_DIR}/../kandinsky/include
        ${CMAKE_CURRENT_SOURCE_DIR}/../omg/include
        ${CMAKE_CURRENT_SOURCE_DIR}/../poincare/include
        ${CMAKE_CURRENT_LIST_DIR}/../python/src  # 绝对路径
        ${CMAKE_CURRENT_LIST_DIR}/../python/port
)

# 直接链接B库（因为B库在同一项目中已定义）
target_link_libraries(${COMPONENT_NAME}
        PUBLIC  # 或 PRIVATE，根据是否要传递依赖
        omg
        ion
        poincare
        kandinsky
        escher
        python
        #gmp
       # mpfi
       # mpfr
       # gcas2
)
# 注册为IDF组件
#idf_component_register(
#        SRCS ${MODULE_SOURCES}
#        INCLUDE_DIRS "."
#            ${CMAKE_CURRENT_LIST_DIR}
#            ${CMAKE_CURRENT_LIST_DIR}/..
#            ${CMAKE_CURRENT_SOURCE_DIR}/../escher/include
#            ${CMAKE_CURRENT_SOURCE_DIR}/../ion/include
#            ${CMAKE_CURRENT_SOURCE_DIR}/../ion/include/ion/keyboard/epsilon
#            ${CMAKE_CURRENT_SOURCE_DIR}/../kandinsky/include
#            ${CMAKE_CURRENT_SOURCE_DIR}/../omg/include
#            ${CMAKE_CURRENT_SOURCE_DIR}/../poincare/include
#            ${CMAKE_CURRENT_LIST_DIR}/../python/src  # 绝对路径
#            ${CMAKE_CURRENT_LIST_DIR}/../python/port
#        REQUIRES
#            omg
#            kandinsky
#            escher
#            ion
#            poincare
#            python
#            giac
#            #gmp
#            #mpfr
#            #mpfi
#)
#
#target_compile_options(${COMPONENT_LIB} PRIVATE -Os)
