#ifndef KANDINSKY_LargeFont_H
#define KANDINSKY_LargeFont_H

/* This file is auto-generated by the rasterizer */

#include "kandinsky/coordinate.h"

class LargeFont {
public:
  constexpr static KDCoordinate k_glyphWidth = 10;
  constexpr static KDCoordinate k_glyphHeight = 18;
};

#endif
