#ifndef KANDINSKY_SmallFont_H
#define KANDINSKY_SmallFont_H

/* This file is auto-generated by the rasterizer */

#include "kandinsky/coordinate.h"

class SmallFont {
public:
  constexpr static KDCoordinate k_glyphWidth = 7;
  constexpr static KDCoordinate k_glyphHeight = 14;
};

#endif
