set(python)

# 源文件列表（支持通配符或明确列表）
set(MODULE_SOURCES
        port/builtins.c
        port/helpers.cpp
        port/mod/ion/modion.cpp
        port/mod/ion/modion_table.cpp
        port/mod/kandinsky/modkandinsky.cpp
        port/mod/kandinsky/modkandinsky_table.c
        port/mod/matplotlib/modmatplotlib.cpp
        port/mod/matplotlib/modmatplotlib_table.c
        port/mod/matplotlib/pyplot/modpyplot.cpp
        port/mod/matplotlib/pyplot/modpyplot_table.c
        port/mod/matplotlib/pyplot/plot_controller.cpp
        port/mod/matplotlib/pyplot/plot_store.cpp
        port/mod/matplotlib/pyplot/pyplot_view.cpp
        port/mod/ndarray.c
        port/mod/ndarray_operators.c
        port/mod/ndarray_properties.c
        port/mod/numpy/approx.c
        port/mod/numpy/carray/carray_tools.c
        port/mod/numpy/compare.c
        port/mod/numpy/create.c
        port/mod/numpy/filter.c
        port/mod/numpy/linalg/linalg_tools.c
        port/mod/numpy/ndarray/ndarray_iter.c
        port/mod/numpy/numerical.c
        port/mod/numpy/numpy.c
        port/mod/numpy/poly.c
        port/mod/numpy/stats.c
        port/mod/numpy/transform.c
        port/mod/numpy/vector.c
        port/mod/time/modtime.cpp
        port/mod/time/modtime_table.c
        port/mod/turtle/modturtle.cpp
        port/mod/turtle/modturtle_table.c
        port/mod/turtle/turtle.cpp
        port/mod/ulab.c
        port/mod/ulab_tools.c
        port/mphalport.c
        port/port.cpp
        port/stackctrl.c
        src/extmod/modurandom.c
        src/py/argcheck.c
        src/py/asmarm.c
        src/py/asmbase.c
        src/py/asmthumb.c
        src/py/asmx64.c
        src/py/asmx86.c
        src/py/asmxtensa.c
        src/py/bc.c
        src/py/binary.c
        src/py/builtinevex.c
        src/py/builtinhelp.c
        src/py/builtinimport.c
        src/py/compile.c
        src/py/emitbc.c
        src/py/emitcommon.c
        src/py/emitglue.c
        src/py/emitinlinethumb.c
        src/py/emitinlinextensa.c
        src/py/emitnarm.c
        src/py/emitnthumb.c
        src/py/emitnx64.c
        src/py/emitnx86.c
        src/py/emitnxtensa.c
        src/py/emitnxtensawin.c
        src/py/formatfloat.c
        src/py/frozenmod.c
        src/py/gc.c
        src/py/lexer.c
        src/py/malloc.c
        src/py/map.c
        src/py/modarray.c
        src/py/modbuiltins.c
        src/py/modcmath.c
        src/py/modcollections.c
        src/py/modgc.c
        src/py/modio.c
        src/py/modmath.c
        src/py/modmicropython.c
        src/py/modstruct.c
        src/py/modsys.c
        src/py/modthread.c
        src/py/moduerrno.c
        src/py/mpprint.c
        src/py/mpstate.c
        src/py/mpz.c
        src/py/nativeglue.c
        src/py/nlr.c
        src/py/nlraarch64.c
        src/py/nlrpowerpc.c
        src/py/nlrsetjmp.c
        src/py/nlrthumb.c
        src/py/nlrx64.c
        src/py/nlrx86.c
        src/py/nlrxtensa.c
        src/py/obj.c
        src/py/objarray.c
        src/py/objattrtuple.c
        src/py/objbool.c
        src/py/objboundmeth.c
        src/py/objcell.c
        src/py/objclosure.c
        src/py/objcomplex.c
        src/py/objdeque.c
        src/py/objdict.c
        src/py/objenumerate.c
        src/py/objexcept.c
        src/py/objfilter.c
        src/py/objfloat.c
        src/py/objfun.c
        src/py/objgenerator.c
        src/py/objgetitemiter.c
        src/py/objint.c
        src/py/objint_longlong.c
        src/py/objint_mpz.c
        src/py/objlist.c
        src/py/objmap.c
        src/py/objmodule.c
        src/py/objnamedtuple.c
        src/py/objnone.c
        src/py/objobject.c
        src/py/objpolyiter.c
        src/py/objproperty.c
        src/py/objrange.c
        src/py/objreversed.c
        src/py/objset.c
        src/py/objsingleton.c
        src/py/objslice.c
        src/py/objstr.c
        src/py/objstringio.c
        src/py/objstrunicode.c
        src/py/objtuple.c
        src/py/objtype.c
        src/py/objzip.c
        src/py/opmethods.c
        src/py/pairheap.c
        src/py/parse.c
        src/py/parsenum.c
        src/py/parsenumbase.c
        src/py/persistentcode.c
        src/py/profile.c
        src/py/pystack.c
        src/py/qstr.c
        src/py/reader.c
        src/py/repl.c
        src/py/ringbuf.c
        src/py/runtime.c
        src/py/runtime_utils.c
        src/py/scheduler.c
        src/py/scope.c
        src/py/sequence.c
        src/py/showbc.c
        src/py/smallint.c
        src/py/stream.c
        src/py/unicode.c
        src/py/vm.c
        src/py/vstr.c
        src/py/warning.c
        )

# 注册为IDF组件
idf_component_register(
        SRCS ${MODULE_SOURCES}
        INCLUDE_DIRS "."
            ${CMAKE_CURRENT_LIST_DIR}/src  # 绝对路径
            ${CMAKE_CURRENT_LIST_DIR}/port
            ${CMAKE_CURRENT_LIST_DIR}/port/mod/include
            ${CMAKE_CURRENT_LIST_DIR}/port/mod/include/numpy
            ${CMAKE_CURRENT_LIST_DIR}/../ion/include
            ${CMAKE_CURRENT_SOURCE_DIR}/../ion/include/ion/keyboard/epsilon
            ${CMAKE_CURRENT_LIST_DIR}/../omg/include
            ${CMAKE_CURRENT_LIST_DIR}/../kandinsky/include
            ${CMAKE_CURRENT_LIST_DIR}/../escher/include
            ${CMAKE_CURRENT_LIST_DIR}/../poincare/include
            ${CMAKE_CURRENT_LIST_DIR}/..
        REQUIRES
            omg
            kandinsky
            escher
            poincare
            ion
)
